---
-  hosts: all
   become: true 
   tasks:
  
   
   - name: install apache and php packages
     apt:
      name:
       - "{{ apache_pakage }}"
       - "{{ php_pakage }}"
      state: latest
      update_cache : yes
   

in inventory file:

172:16:250:132 apache_package=apache2 php_package=libapache2-mod-php
172:16:250:133 apache_package=apache  php_package=httpd  
